"""Central settings. Every path is relative to the project folder, so the
project runs from any location (no more C:\\Users\\... paths)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "database" / "businessiq.db"
RAW_XLSX = ROOT / "data" / "Business_IQ_Sales_raw.xlsx"
CLEAN_XLSX = ROOT / "data" / "Business_IQ_Sales_Cleaned_v2.xlsx"

CURRENCY = "₹"            # change to "$", "€" etc. if you prefer
ORDERS_PER_MINUTE = 6.0   # average simulated order rate (live feed + history)
HISTORY_DAYS = 14         # days of history generated by build_database.py
